spring:
  data:
    mongodb:
      username: yuosef
      password: yuosef
      host: localhost
      port: 27017
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.yuosef.ecommerce.Kafka.OrderConfirmation,paymentConfirmation:com.yuosef.ecommerce.Notifications.PaymentNotificationRequest
  mail:
    host: localhost
    port: 1025
    username: yuosef
    password: yuosef
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectionimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040